// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	douyin_core "gateway/biz/router/douyin/core"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	douyin_core.Register(r)
}
