# Generated by gen-dockerfile.sh

# Go builder
FROM golang:1.19.6-alpine3.17@sha256:f2e0acaf7c628cd819b73541d7c1ea8f888d51edb0a58935a3c46a084fa953fa AS builder
WORKDIR /m
COPY . .
RUN apk update && apk add --no-cache git make
RUN go env -w GO111MODULE="on" && go env -w GOPROXY="https://goproxy.cn,direct" && sh scripts/for-all.sh go mod download
# RUN go mod verify # does not work with go.work
RUN sh scripts/for-all.sh make -B

# Service containers

FROM alpine AS md-counter
RUN adduser -D -u 1000 md-user
USER md-user
COPY --from=builder /m/counter/output /
CMD ["sh", "/bootstrap.sh"]

FROM alpine AS md-feeder
RUN adduser -D -u 1000 md-user
USER md-user
COPY --from=builder /m/feeder/output /
CMD ["sh", "/bootstrap.sh"]

FROM jrottenberg/ffmpeg:5-alpine AS md-gateway
RUN adduser -D -u 1000 md-user && mkdir /storage && chown md-user /storage
USER md-user
COPY --from=builder /m/gateway/bin/gateway /
EXPOSE 8000
ENTRYPOINT []
CMD ["/gateway", "--storage", "/storage"]

FROM alpine AS md-message
RUN adduser -D -u 1000 md-user
USER md-user
COPY --from=builder /m/message/output /
CMD ["sh", "/bootstrap.sh"]

FROM alpine AS md-reaction
RUN adduser -D -u 1000 md-user
USER md-user
COPY --from=builder /m/reaction/output /
CMD ["sh", "/bootstrap.sh"]

