#!/bin/sh

echo "# Generated by gen-docker-compose.sh

version: \"3.9\"

services:
  cassandra:
    image: \"cassandra:latest\"
    environment:
      - HEAP_NEWSIZE=512M
      - MAX_HEAP_SIZE=512M
    volumes:
      - nosql:/var/lib/cassandra
    networks:
      - mdouyin
    healthcheck:
      test: [\"CMD\", \"nodetool\", \"statusgossip\"]

  etcd:
    image: \"bitnami/etcd:latest\"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    networks:
      - mdouyin
    healthcheck:
      test: [\"CMD\", \"etcdctl\", \"endpoint\", \"health\"]

  mysql:
    image: \"mariadb:latest\"
    environment:
      - MARIADB_USER=mdouyin
      - MARIADB_PASSWORD=mdouyin
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=mdouyin
    volumes:
      - db:/var/lib/mysql
    networks:
      - mdouyin
    healthcheck:
      test: [\"CMD\", \"mysqladmin\" ,\"ping\", \"-h\", \"localhost\"]

  redis:
    image: \"bitnami/redis:latest\"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./scripts/redis.conf:/opt/bitnami/redis/mounted-etc/overrides.conf:ro
    networks:
      - mdouyin
    healthcheck:
      test: [\"CMD\", \"redis-cli\" ,\"ping\"]
"

for package in $(grep "/" "go.work" | sed -e "s#.\+/##"); do
    if [ "$package" = "common" ]; then
        continue
    fi

    echo "  $package:"
    if [ "$package" = "gateway" ]; then
        echo "    ports:
      - \"8000:8000\"
    volumes:
      - media:/storage"
    fi
    echo "    build:
      context: .
      target: md-$package
    environment:
      - ENV_MDOUYIN_ETCD=etcd:2379
      - ENV_MDOUYIN_SECRET=123456789abcde
      - ENV_MDOUYIN_CASSANDRA=cassandra
      - ENV_MDOUYIN_BASE=http://localhost:8000
      - ENV_MDOUYIN_REDIS=redis:6379
      - ENV_MDOUYIN_RDBMS=mdouyin:mdouyin@tcp(mysql:3306)/mdouyin?charset=utf8mb4&parseTime=True&loc=Local
    networks:
      - mdouyin
    depends_on:
      cassandra:
        condition: service_healthy
      etcd:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
"
done

echo "networks:
  mdouyin:
    driver: bridge

volumes:
  db:
  media:
  nosql:
"
