#!/bin/sh

hash="f2e0acaf7c628cd819b73541d7c1ea8f888d51edb0a58935a3c46a084fa953fa"

echo "# Generated by gen-dockerfile.sh

# Go builder
FROM golang:1.19.6-alpine3.17@sha256:${hash} AS builder
WORKDIR /m
COPY . .
RUN apk update && apk add --no-cache git make
RUN go env -w GO111MODULE=\"on\" && go env -w GOPROXY=\"https://goproxy.cn,direct\" \
&& sh scripts/for-all.sh go mod download
# RUN go mod verify # does not work with go.work
RUN sh scripts/for-all.sh make -B
"

echo "# Service containers
"

for package in $(grep "/" "go.work" | sed -e "s#.\+/##"); do
    if [ "$package" = "common" ]; then
        continue
    fi

    if [ "$package" = "gateway" ]; then
        echo "FROM jrottenberg/ffmpeg:5-alpine AS md-${package}
RUN adduser -D -u 1000 md-user && mkdir /storage && chown md-user /storage
USER md-user
COPY --from=builder /m/gateway/bin/gateway /
EXPOSE 8000
ENTRYPOINT []
CMD [\"/gateway\", \"--storage\", \"/storage\"]
"
    else
        echo "FROM alpine AS md-${package}
RUN adduser -D -u 1000 md-user
USER md-user
COPY --from=builder /m/${package}/output /
CMD [\"sh\", \"/bootstrap.sh\"]
"
    fi
done
