// Code generated by hertz generator.

package core

import (
	"context"

	core "gateway/biz/model/douyin/core"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Chat .
// @router /douyin/message/chat/ [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.DouyinMessageChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core.DouyinMessageChatResponse)

	c.JSON(consts.StatusOK, resp)
}

// Message .
// @router /douyin/message/action/ [POST]
func Message(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.DouyinMessageActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core.DouyinMessageActionResponse)

	c.JSON(consts.StatusOK, resp)
}
