// Code generated by Kitex v0.4.4. DO NOT EDIT.

package messageservice

import (
	rpc "common/kitex_gen/douyin/rpc"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Chat(ctx context.Context, req *rpc.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *rpc.DouyinMessageChatResponse, err error)
	Message(ctx context.Context, req *rpc.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *rpc.DouyinMessageActionResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kMessageServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kMessageServiceClient struct {
	*kClient
}

func (p *kMessageServiceClient) Chat(ctx context.Context, req *rpc.DouyinMessageChatRequest, callOptions ...callopt.Option) (r *rpc.DouyinMessageChatResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Chat(ctx, req)
}

func (p *kMessageServiceClient) Message(ctx context.Context, req *rpc.DouyinMessageActionRequest, callOptions ...callopt.Option) (r *rpc.DouyinMessageActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Message(ctx, req)
}
